### ISSUE TITLE
Cast value expects nested index to also index db model

### ISSUE THREAD

**Issue by tinco** [NoBrainerORM/nobrainer#223] opened 2016-08-03 00:08 UTC
If I define a custom type for a field that gets set by the user as Hash, but is stored in RethinkDB as an Array (so it can be used as a primary key) this messes up cast_value which expects the result of `cast_user_to_db_for` to return a Hash when the value is used as a parameter in a find.

In my model `Location` is such a field that uniquely identifies a cell:

```
SpreadSheetCellsChannel#set_cell_value({"location"=>{"r"=>1, "c"=>2}, "value"=>"c"})
```

This is the operator that fails, apparently it splits up the location in a 'r' and a 'c' before casting. The query is a simple `.find(location)`:

```
This is: #<struct NoBrainer::Criteria::Where::BinaryOperator key_path=[:location, :r], key_modifier=:scalar, op=:eq, value=1, model=SpreadsheetCell, casted_values=false>
```

This is the full error:

```
[TypeError - no implicit conversion of Symbol into Integer]: 
/Users/tinco/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.32.0/lib/no_brainer/criteria/where.rb:189:in `[]' | 
/Users/tinco/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.32.0/lib/no_brainer/criteria/where.rb:189:in `block in cast_value' |
/Users/tinco/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.32.0/lib/no_brainer/criteria/where.rb:189:in `each' | 
/Users/tinco/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.32.0/lib/no_brainer/criteria/where.rb:189:in `reduce' | 
/Users/tinco/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.32.0/lib/no_brainer/criteria/where.rb:189:in `cast_value'
```

I looked at the source and I don't think there's a trivial solution for this. The casting simply relies on information it can't have right now. It has to be rewritten to cast the field as a whole instead of casting its subpaths one by one.

**Comment by nviennot** [comment] 2016-08-03 02:53
Provide me with a piece of standalone source code so I can reproduce the issue. See an example here: https://github.com/nviennot/nobrainer/issues/220#issuecomment-233541287

Thanks!

**Comment by nviennot** [comment] 2016-08-03 03:02
Also, you might find helpful to be explicit about the equal, e.g. `where(:location.eq => {:r => 1, :c => 2})`

**Comment by tinco** [comment] 2016-08-03 13:03
I'm on a tight deadline right now, I'll make a repro tomorrow. For now I've fixed it by adding a constructor that used an array and then creating the location with that array so nobrainer doesn't get confused.

**Comment by tinco** [comment] 2016-08-03 13:52
Ugh.. the workaround doesn't work for upsert:

```
[
  RethinkDB::ReqlDriverCompileError -
    r.expr can't handle #<struct SpreadsheetCell::Location r=2, c=2> of class SpreadsheetCell::Location.]: 
 /Users/tinco/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.3.0.0/lib/shim.rb:147:in `fast_expr' |
 /Users/tinco/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.3.0.0/lib/shim.rb:156:in `expr' | 
 /Users/tinco/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.3.0.0/lib/func.rb:113:in `block (3 levels) in <class:RQL>' |
 /Users/tinco/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.3.0.0/lib/func.rb:113:in `map' |
 /Users/tinco/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.3.0.0/lib/func.rb:113:in `block (2 levels) in <class:RQL>
```

**Comment by nviennot** [comment] 2016-08-03 15:45
Yeah, I still have no clue what's the problem you are talking about. I have no understanding on how to reproduce any of it.

**Comment by zedtux** [comment] 2021-02-25 19:24
@tinco I'm closing this issue due to its age, as I guess it is no more relevant. If otherwise, please feel free to update it!

**Closed by zedtux** 2021-02-25 19:24 UTC
