### ISSUE TITLE
Eager loading on polymorphic models

### ISSUE THREAD

**Issue by mmuehlberger** [NoBrainerORM/nobrainer#239] opened 2017-06-26 13:49 UTC
Polymorphism with NoBrainer works great, for normal queries, but I need eager_loading, to speed up the code.

Right now it isn't possible to `eager_load` an association on a subclass, because NoBrainer always fetches the associations from `root_class`, which leads to an `Unknown association` error. This means, I can't preload any data and the library will load each model individually.

Is there a possible workaround for this, or will this be a feature in the future?

**Comment by nviennot** [comment] 2017-06-26 14:03
It should work if you declare the association that you are trying to load in the root class

**Comment by mmuehlberger** [comment] 2017-06-26 14:05
That much I know, my issue is, that I can't do that.

**Comment by nviennot** [comment] 2017-06-26 14:07
Can you provide a standalone script that would reproduce the issue? If so, it'll be much easier to me to make a fix
Thank you :))

**Comment by zedtux** [comment] 2021-02-25 19:41
I'm closing this issue due to its age but in the case it looks still relevant, please feel free to update it!

**Closed by zedtux** 2021-02-25 19:41 UTC
Labels: question
